# Generated by Django 4.2.5 on 2023-10-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
