# Generated by Django 4.2.5 on 2023-10-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.TextField(default='def', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.TextField(default='def', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.TextField(default='def', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.TextField(default='def', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
