# Generated by Django 4.2.5 on 2023-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_question_subject_subject_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='Subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.subject'),
            preserve_default=False,
        ),
    ]
