# Generated by Django 4.2.5 on 2023-10-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_subject_question_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Subject',
            new_name='subject',
        ),
    ]
